application: wildlabglass
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /config.php
  script: config.php

- url: /attachment-proxy.php
  script: attachment-proxy.php

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /mirror-client.php
  script: mirror-client.php

- url: /notify.php
  script: notify.php

- url: /oauth2callback.php
  script: oauth2callback.php

- url: /signout.php
  script: signout.php

- url: /util.php
  script: util.php

#- url: /google-api-php-client/examples/plus/index.php
#  script: google-api-php-client/examples/plus/index.php
  
#- url: /
#  script: index.php

#- url: /experiments/db_test.php
#  script: experiments/db_test.php

- url: /insertMostRecentSightingAllUsers.php
  script: insertMostRecentSightingAllUsers.php

- url: /insertMostRecentSightingMe.php
  script: insertMostRecentSightingMe.php

#- url: /wildlab-glass-lib/examples/sightingsTest.php
#  script: wildlab-glass-lib/examples/sightingsTest.php

#- url: /
#  script: index_all.php

- url: /
  script: index.php
